### ISSUE TITLE
Currency symbol is throwing off form validation.

### ISSUE THREAD

**Issue by Blackbaud-AlexKingman** [blackbaud/skyux-autonumeric#17]
# Actual behavior
1. Create a *required* autonumeric input with the following options:
`currencySymbol: '$'`
2. Init the form with an empty value.
3. click on the form, then click out.
4. notice the form's value become `0` and is marked valid.

# Expected behavior
Value should still be empty and marked invalid.

**Comment by Blackbaud-TrevorBurch** [comment]
In `3.0.4`
