### ISSUE TITLE
SkyAutonumeric: 'max', 'maxLength' not working with skyAutonumeric

### ISSUE THREAD

**Issue by Blackbaud-UdaySharma** [blackbaud/skyux-autonumeric#34]
I'm unable to set max length or value for a field where skyAutoNumeric directive is applied. It seems to be setting it's own max length of 13 digits left of the decimal. We want to set a max limit less than that.
![image](https://user-images.githubusercontent.com/69636211/90142856-84be7d80-dd9a-11ea-906e-66a8420c8a58.png)

**Comment by Blackbaud-SteveBrush** [comment]
@Blackbaud-UdaySharma It looks like this is the intended behavior of `autoNumeric`. See: https://github.com/autoNumeric/autoNumeric/issues/599#issuecomment-415307899

Does this work for you?
